### ISSUE TITLE
Titulo Home 

### ISSUE THREAD

**Issue by syelmini** [gastonyelmini/latio-core#1]
- Poner "JOIN US IN THE INNOVATION ERA" en **bold**.
- Subtítulo en **Italics**.

<img width="806" alt="captura de pantalla 2018-03-21 a la s 20 11 44" src="https://user-images.githubusercontent.com/37640690/37742380-1bd98020-2d44-11e8-8941-b1e561a32ad1.png">

**Comment by gastonyelmini** [comment]
Issue cerrado.
\
![captura de pantalla 2018-03-25 a la s 21 12 50](https://user-images.githubusercontent.com/13191932/37881616-593641c6-3071-11e8-9b75-594933d0077a.png)
